"""Artifact Appendix and submission-checklist mapping.

Turns a deterministic scan into the artifacts a researcher actually needs at a
submission deadline: an ACM-style Artifact Appendix skeleton and a table that
maps rrdoctor findings to the ACM badge tiers and the NeurIPS reproducibility
checklist. This is the "bind to the painful moment" layer.
"""

from __future__ import annotations

from dataclasses import dataclass

from rrdoctor.models import ScanReport

# Rule IDs whose *failure* blocks a given ACM Artifact Evaluation badge tier.
# Badges are cumulative: Functional implies Available, Reproduced implies Functional.
ACM_BADGE_RULES: dict[str, tuple[str, ...]] = {
    "Artifact Available": ("RRD010", "RRD020", "RRD021", "RRD100", "RRD101"),
    "Artifact Functional": ("RRD001", "RRD002", "RRD030", "RRD031", "RRD034", "RRD050"),
    "Results Reproduced": ("RRD004", "RRD040", "RRD051", "RRD052", "RRD053", "RRD054"),
}

# NeurIPS-style reproducibility checklist items mapped to the rule IDs that
# provide evidence for them.
NEURIPS_CHECKLIST: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Code is provided with instructions to reproduce the main results", ("RRD002", "RRD050")),
    ("All training/eval details and dependencies are specified", ("RRD030", "RRD031", "RRD034")),
    ("Random seeds and sources of randomness are reported", ("RRD052",)),
    ("Compute resources (GPU/CUDA) are described", ("RRD054",)),
    ("Data is documented and access is described", ("RRD040", "RRD041")),
    ("Results provenance is recorded", ("RRD053",)),
    ("A license is included", ("RRD010",)),
)


@dataclass(frozen=True)
class TierStatus:
    """Readiness of a single badge tier."""

    name: str
    blocking_rule_ids: list[str]

    @property
    def ready(self) -> bool:
        return not self.blocking_rule_ids


def _failed_rule_ids(report: ScanReport) -> set[str]:
    """Rule IDs that produced an error or warning finding."""

    return {f.rule_id for f in report.findings if f.severity.value in ("error", "warning")}


def badge_status(report: ScanReport) -> list[TierStatus]:
    """Compute per-tier readiness from a scan report."""

    failed = _failed_rule_ids(report)
    tiers: list[TierStatus] = []
    for name, rule_ids in ACM_BADGE_RULES.items():
        blocking = [rid for rid in rule_ids if rid in failed]
        tiers.append(TierStatus(name=name, blocking_rule_ids=blocking))
    return tiers


def render_checklist(report: ScanReport) -> str:
    """Render the ACM/NeurIPS mapping table as Markdown."""

    failed = _failed_rule_ids(report)
    lines = [
        "# Submission readiness - checklist mapping",
        "",
        f"- Repository: `{report.repository_path}`",
        f"- Profile: `{report.profile}`",
        f"- Score: **{report.score}/100**",
        "",
        "## ACM Artifact Evaluation badges",
        "",
        "| Badge | Status | Blocking checks |",
        "| --- | --- | --- |",
    ]
    for tier in badge_status(report):
        status = "ready" if tier.ready else "action needed"
        blocking = ", ".join(tier.blocking_rule_ids) if tier.blocking_rule_ids else "-"
        lines.append(f"| {tier.name} | {status} | {blocking} |")

    lines.extend(
        [
            "",
            "## NeurIPS reproducibility checklist",
            "",
            "| Item | Status | Evidence checks |",
            "| --- | --- | --- |",
        ]
    )
    for item, rule_ids in NEURIPS_CHECKLIST:
        blocking_ids = [rid for rid in rule_ids if rid in failed]
        status = "OK" if not blocking_ids else "TODO"
        evidence = ", ".join(rule_ids)
        lines.append(f"| {item} | {status} | {evidence} |")

    lines.extend(
        [
            "",
            "> Mapping is heuristic. An OK means rrdoctor found no blocking issue for that "
            "item; it does not certify the artifact. Reviewers make the final call.",
            "",
        ]
    )
    return "\n".join(lines)


def _badge_summary(report: ScanReport) -> str:
    ready = [t.name for t in badge_status(report) if t.ready]
    if not ready:
        return "No tier is clear yet - see the blocking checks below."
    return "On track for: " + ", ".join(ready) + "."


def render_appendix(report: ScanReport) -> str:
    """Render an ACM-style Artifact Appendix skeleton, pre-filled where possible.

    Sections rrdoctor cannot infer are left as explicit TODOs so the author fills
    them in rather than shipping blanks.
    """

    failed = _failed_rule_ids(report)

    def todo_if(rule_id: str, satisfied: str, missing: str) -> str:
        return satisfied if rule_id not in failed else f"TODO: {missing}"

    lines = [
        "# Artifact Appendix",
        "",
        "<!-- Generated by rrdoctor. Edit before submitting; TODOs mark gaps the",
        "     scanner could not fill automatically. -->",
        "",
        "## Abstract",
        "",
        "TODO: One paragraph describing what the artifact contains and which paper "
        "claims it supports.",
        "",
        "## Artifact check-list (meta-information)",
        "",
        "- **Algorithm:** TODO",
        "- **Program:** TODO",
        "- **Data set:** "
        + todo_if("RRD040", "See documented data availability.", "describe datasets and access."),
        "- **Run-time environment:** "
        + todo_if(
            "RRD030", "Declared dependency manifest is present.", "list OS and dependencies."
        ),
        "- **Hardware:** "
        + todo_if("RRD054", "CPU/GPU requirements documented.", "state required GPU/CUDA, if any."),
        "- **Metrics:** TODO",
        "- **Output:** "
        + todo_if("RRD053", "Results provenance is recorded.", "describe expected outputs."),
        "- **Experiments:** "
        + todo_if(
            "RRD050", "Experiment entrypoint is present.", "name the reproduction entrypoint."
        ),
        "- **How much disk space required (approximately)?:** TODO",
        "- **How much time is needed to prepare workflow (approximately)?:** TODO",
        "- **How much time is needed to complete experiments (approximately)?:** TODO",
        "- **Publicly available?:** "
        + todo_if("RRD010", "Yes - license included.", "add a license before archiving."),
        "- **Archived (provide DOI)?:** TODO: deposit on Zenodo/Figshare/Dryad and add the DOI.",
        "",
        "## Description",
        "",
        "### How to access",
        "",
        todo_if(
            "RRD101",
            "Tagged release / version metadata is available.",
            "tag a release and archive it for a citable DOI.",
        ),
        "",
        "### Hardware dependencies",
        "",
        todo_if("RRD054", "Documented in the README.", "state CPU/GPU/CUDA requirements."),
        "",
        "### Software dependencies",
        "",
        todo_if(
            "RRD031",
            "Runtime version and dependency manifest are documented.",
            "pin a runtime version and list dependencies.",
        ),
        "",
        "### Data sets",
        "",
        todo_if(
            "RRD040",
            "Data availability is documented.",
            "document datasets and how to obtain them.",
        ),
        "",
        "### Models",
        "",
        "TODO: Describe any pretrained models/weights and where to obtain them.",
        "",
        "## Installation",
        "",
        todo_if(
            "RRD002",
            "See the README setup section.",
            "add setup/installation steps to the README.",
        ),
        "",
        "## Experiment workflow",
        "",
        todo_if(
            "RRD050",
            "Run the documented experiment entrypoint.",
            "document how to run experiments.",
        ),
        "",
        "## Evaluation and expected results",
        "",
        todo_if(
            "RRD004",
            "See the README reproducibility section for expected results.",
            "describe the key results to reproduce and tolerances.",
        ),
        "",
        "## Notes",
        "",
        f"_{_badge_summary(report)}_",
        "",
    ]
    return "\n".join(lines)
